[package]
name = "webrogue-launcher"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
winit = ["dep:winit", "dep:webrogue-wasmtime", "dep:webrogue-gfx-winit", "dep:webrogue-virgl", "webrogue-virgl/lib-impl"]

[dependencies]
wry = { workspace = true, default-features = true }
# tao = { workspace = true, default-features = true }
winit = { workspace = true, default-features = true, optional = true }
dpi = { workspace = true, default-features = false }
json-escape = { workspace = true }
webrogue-launcher-server-openapi = { workspace = true, default-features = true }
axum = { version = "0.8" }
axum-extra = { workspace = true, features = ["cookie", "query"] }
http = { version = "*" }
async-trait = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-service = "0.3"
bytes = "1.0"
tokio-stream = { workspace = true }
tower-http = { version = "*", features = ["cors"] }
lazy_static = { workspace = true }
futures-util = { workspace = true }
webrtc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
webrogue-hub-client = { workspace = true }
blake3 = { workspace = true }
webrogue-wrapp = { workspace = true }
webrogue-wasmtime = { workspace = true, features = ["jit"], optional = true }
webrogue-gfx-winit = { workspace = true, optional = true }
webrogue-virgl = { workspace = true, optional = true }
headers = { workspace = true }
rand = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
tokio-util = { workspace = true, features = ["rt"] }
webrogue-hub-debuggee = { workspace = true }
rustls = { workspace = true, features = ["aws_lc_rs"] }
tracing.workspace = true
futures = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
wry = { workspace = true, features = ["linux-body"] }

[build-dependencies]
reqwest = { workspace = true, features = ["blocking"] }
