[files]
extend-exclude = [
    "/webrogue-sdk",
    "/external",
    "*.storyboard",
    "/crates/wasi-common",
    "/crates/virgl-lib/epoxy",
    "/crates/virgl-lib/compat",
]
ignore-vcs = true

[default.extend-words]
wrapp = "wrapp"
