[package]
name = "webrogue-wasmtime"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
jit = ["wasmtime/cranelift", "wasmtime/parallel-compilation", "wasmtime/addr2line"]
aot = ["dep:webrogue-aot-data"]
cache = ["wasmtime/cache"] # TODO "wasmtime/incremental-cache"
async = ["wasmtime/async"]
debug = ["wasmtime/debug", "wasmtime/debug-builtins"] # 

[dependencies]
webrogue-gfx = { workspace = true }
webrogue-virgl = { workspace = true }
anyhow = { workspace = true }
webrogue-wrapp = { workspace = true }
webrogue-wasip1 = { workspace = true }
wasmtime = { workspace = true, default-features = false, features = ["runtime", "threads", "gc", "gc-drc", "anyhow", "component-model"] }
webrogue-wasi-common = { workspace = true, default-features = false, features = ["sync"] }
wiggle = { workspace = true, default-features = false, features = ["wasmtime"] }
webrogue-aot-data = { workspace = true, optional = true }
gdbstub_arch = { workspace = true }
futures = { workspace = true }
