pub const EXCLUDED: [&str; 35] = [
    "glGetString",
    // "glBindAttribLocation",
    "glBufferSubData",
    "glCompressedTexImage2D",
    "glCompressedTexSubImage2D",
    "glDeleteBuffers",
    "glDeleteFramebuffers",
    "glDeleteRenderbuffers",
    "glDeleteTextures",
    "glDrawElements",
    "glGenFramebuffers",
    "glGenRenderbuffers",
    "glGenTextures",
    "glGetActiveAttrib",
    "glGetActiveUniform",
    "glGetAttachedShaders",
    "glGetBooleanv",
    "glGetBufferParameteriv",
    "glGetFloatv",
    "glGetFramebufferAttachmentParameteriv",
    "glGetIntegerv",
    "glGetRenderbufferParameteriv",
    "glGetShaderPrecisionFormat",
    "glGetShaderSource",
    "glGetTexParameterfv",
    "glGetTexParameteriv",
    // "glGetUniformLocation",
    "glGetUniformfv",
    "glGetUniformiv",
    "glGetVertexAttribPointerv",
    "glGetVertexAttribfv",
    "glGetVertexAttribiv",
    "glReadPixels",
    "glTexImage2D",
    "glTexParameterfv",
    "glTexParameteriv",
    "glTexSubImage2D",
];

pub const MANUAL_IMPL: [&str; 5] = [
    // "glGenBuffers",
    "glShaderSource",
    "glGetAttribLocation",
    "glVertexAttribPointer",
    "glBindAttribLocation",
    "glGetUniformLocation",
];
