cd $(dirname $0)/..
set -ex


make -C webrogue-sdk/libraries/Vulkan-Docs/xml/ install
cp webrogue-sdk/libraries/Vulkan-Docs/xml/vk.xml webrogue-sdk/libraries/mesa/src/vulkan/registry/vk.xml
make -C webrogue-sdk/libraries/Vulkan-Headers/ --file=Makefile.release update-headers
cp webrogue-sdk/libraries/Vulkan-Headers/include/vulkan/*.h webrogue-sdk/libraries/mesa/include/vulkan
cp webrogue-sdk/libraries/Vulkan-Headers/include/vk_video/*.h webrogue-sdk/libraries/mesa/include/vk_video
cp webrogue-sdk/libraries/Vulkan-Headers/include/vulkan/*.h webrogue-sdk/libraries/SDL2/src/video/khronos/vulkan
cp webrogue-sdk/libraries/Vulkan-Headers/include/vulkan/*.h webrogue-sdk/libraries/SDL3/src/video/khronos/vulkan

# cp webrogue-sdk/libraries/Vulkan-Docs/xml/vk.xml webrogue-sdk/libraries/venus-protocol/xmls/vk.xml
cd webrogue-sdk/libraries/venus-protocol
# python3 utils/print_vk_command_types.py >xmls/VK_EXT_command_serialization.xml.2
echo "/* This file is generated by venus-protocol git-$(git rev-parse --short=8 HEAD) (Webrogue fork). */\n" >templates/banner.in.webrogue
python3 vn_protocol.py --outdir ../mesa/src/virtio/venus-protocol --banner templates/banner.in.webrogue

python3 vn_protocol.py --outdir ../../../external/virglrenderer/src/venus/venus-protocol --banner templates/banner.in.webrogue --renderer
rm templates/banner.in.webrogue
cp ../Vulkan-Headers/include/vulkan/vulkan.h ../Vulkan-Headers/include/vulkan/vulkan_webrogue.h ../Vulkan-Headers/include/vulkan/vulkan_core.h ../../../external/virglrenderer/src/venus/venus-protocol 