name:  Build Webrogue CLI utility

on:
  workflow_call:

jobs:
  linux_artifacts:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
        - artifact: Artifacts-Linux-GNU-x86_64
          runner: ubuntu-24.04
          libc: gnu
        - artifact: Artifacts-Linux-GNU-aarch64
          runner: ubuntu-24.04-arm
          libc: gnu
        - artifact: Artifacts-Linux-MUSL-x86_64
          runner: ubuntu-24.04
          libc: musl
        - artifact: Artifacts-Linux-MUSL-aarch64
          runner: ubuntu-24.04-arm
          libc: musl

    steps:
    - uses: actions/checkout@v7

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/virglrenderer external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Build AOT artifacts
      run: |
        COMPONENTS=template LIBCS=${{ matrix.libc }} sh linux/build.sh

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact }}
        retention-days: 1
        if-no-files-found: error
        path: aot_artifacts

  windows_artifacts:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
        - runner: windows-11-arm
          rust_arch: x86_64
          win_arch: x64
          artifact: Artifacts-Windows-x86_64
        - runner: windows-11-arm
          rust_arch: aarch64
          win_arch: arm64
          artifact: Artifacts-Windows-aarch64

    steps:
    - uses: actions/checkout@v7

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/virglrenderer external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Setup Python
      run: |
        python3 -m pip install requests

    - name: Install Rust target
      run: |
        rustup target add ${{ matrix.rust_arch }}-pc-windows-msvc

    - name: Build AOT artifacts
      shell: cmd 
      run: |
        for /f "usebackq tokens=*" %%i in (`vswhere -latest -find Common7\Tools\VsDevCmd.bat`) do (
          call "%%i"
        )
        python3 windows/msvc/build_template.py ${{ matrix.rust_arch }} ${{ matrix.win_arch }} || exit /b 1

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact }}
        retention-days: 1
        if-no-files-found: error
        path: aot_artifacts

  android_artifacts:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v7

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/virglrenderer external/zstd-rs webrogue-sdk
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Setup Rust
      run: |
        rustup target add aarch64-linux-android
  
    - name: Build AOT artifacts
      run: |
        sh android/runtime/build_native_code.sh aot
        sh android/template/build_template.sh

    - uses: actions/upload-artifact@v7
      with:
        name: Artifacts-Android
        retention-days: 1
        if-no-files-found: error
        path: aot_artifacts

  apple_artifacts:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v7

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/virglrenderer external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Install Xcodegen
      run: |
        brew install xcodegen
    
    - name: Setup Rust
      run: |
        rustup target add x86_64-apple-darwin
        rustup target add x86_64-apple-ios
        rustup target add aarch64-apple-darwin
        rustup target add aarch64-apple-ios
        rustup target add aarch64-apple-ios-sim
  
    - name: Build AOT artifacts
      run: |
        sh apple/template/build_template.sh

    - uses: actions/upload-artifact@v7
      with:
        name: Artifacts-Apple
        retention-days: 1
        if-no-files-found: error
        path: aot_artifacts

  linux-cli:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
        - arch: x86_64
          runner: ubuntu-24.04
          artifact: CLI-linux-x86_64-glibc-raw
          libc: gnu
        - arch: aarch64
          runner: ubuntu-24.04-arm
          artifact: CLI-linux-aarch64-glibc-raw
          libc: gnu
        - arch: x86_64
          runner: ubuntu-24.04
          artifact: CLI-linux-x86_64-musl-raw
          libc: musl
        - arch: aarch64
          runner: ubuntu-24.04-arm
          artifact: CLI-linux-aarch64-musl-raw
          libc: musl

    steps:
    - uses: actions/checkout@v7

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/virglrenderer external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Build
      run: |
        COMPONENTS=cli LIBCS=${{ matrix.libc }} sh linux/build.sh

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact }}
        retention-days: 1
        if-no-files-found: error
        path: linux/${{ matrix.libc }}/${{ matrix.arch }}/target/${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}/cli/webrogue

  macos-arm64-cli:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v7

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/virglrenderer external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Setup Rust
      run: |
        rustup target add aarch64-apple-darwin
  
    - name: Build
      run: |
        cargo build --profile=cli --target=aarch64-apple-darwin --features=full

    - uses: actions/upload-artifact@v7
      with:
        name: CLI-macOS-arm64-raw
        retention-days: 1
        if-no-files-found: error
        path: target/aarch64-apple-darwin/cli/webrogue

  macos-x86_64-cli:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v7

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/virglrenderer external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Setup Rust
      run: |
        rustup target add x86_64-apple-darwin
  
    - name: Build
      run: |
        cargo build --profile=cli --target=x86_64-apple-darwin --features=full

    - uses: actions/upload-artifact@v7
      with:
        name: CLI-macOS-x86_64-raw
        retention-days: 1
        if-no-files-found: error
        path: target/x86_64-apple-darwin/cli/webrogue

  windows-cli:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
        - runner: windows-11-arm
          arch: x86_64
          artifact: CLI-windows-x86_64-raw
        - runner: windows-11-arm
          arch: aarch64
          artifact: CLI-windows-aarch64-raw

    steps:
    - uses: actions/checkout@v7

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/virglrenderer external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Install Rust target
      run: |
        rustup target add ${{ matrix.arch }}-pc-windows-msvc

    - name: Build
      shell: cmd 
      run: |
        for /f "usebackq tokens=*" %%i in (`vswhere -latest -find Common7\Tools\VsDevCmd.bat`) do (
          call "%%i"
        )
        REM gfxstream doesn't seem to support MSVC
        set CC=clang-cl
        set CXX=clang-cl
        cargo build --target=${{ matrix.arch }}-pc-windows-msvc --features=full --profile cli  || exit /b 1

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact }}
        retention-days: 1
        if-no-files-found: error
        path: target/${{ matrix.arch }}-pc-windows-msvc/cli/webrogue.exe
