name: Webrogue CI

on: 
  pull_request:
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04-arm
          components: cli,aot-lib
        - os: windows-11-arm
          components: cli,aot-lib
        - os: macos-26
          components: cli,aot-lib
        - os: macos-26
          components: ios,macos
        - os: ubuntu-24.04 # There is no NDK build for AArch64 Linux. Shame on you, Google.
          components: android

    steps:
    - uses: actions/checkout@v7

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/virglrenderer external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - uses: taiki-e/install-action@v2.87.6
      with:
        tool: cargo-ndk

    - name: Install Rust toolchains (macOS)
      if: startsWith(matrix.os, 'macos') == true && contains(matrix.components, 'cli') == true
      run: |
        rustup target add aarch64-apple-darwin
        # rustup target add x86_64-apple-darwin

    - name: Install Rust toolchains (Windows)
      if: startsWith(matrix.os, 'windows') == true && contains(matrix.components, 'cli') == true
      run: |
        rustup target add x86_64-pc-windows-msvc

    - name: Install Rust toolchains (Android)
      if: contains(matrix.components, 'android') == true
      run: |
        rustup target add aarch64-linux-android
        rustup target add x86_64-linux-android
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

    - name: Install Rust toolchains (iOS)
      if: contains(matrix.components, 'ios') == true
      run: |
        rustup target add aarch64-apple-ios
        rustup target add aarch64-apple-ios-sim
        rustup target add x86_64-apple-ios

    - name: Run test scripts (on UNIX)
      if: startsWith(matrix.os, 'windows') == false
      run: |
        COMPONENTS=${{ matrix.components }} python3 scripts/cargo_check.py
        cargo test --package webrogue-wasip1

    - name: Run test scripts (on Windows)
      if: startsWith(matrix.os, 'windows') == true
      shell: cmd
      run: |
        for /f "usebackq tokens=*" %%i in (`vswhere -latest -find Common7\Tools\VsDevCmd.bat`) do (
          call "%%i"
        )
        REM gfxstream doesn't seem to support MSVC
        set CXX=clang-cl
        set CC=clang-cl
        set COMPONENTS=${{ matrix.components }}
        python3 scripts\cargo_check.py || exit /b 1
        cargo test --package webrogue-wasip1 || exit /b 1

  typos:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v7

    - name: Install and run typos-cli
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        cargo binstall --locked typos-cli
        typos

  # Additional checks
  # build_cli:
  #   needs: [ tests, typos ]
  #   uses: ./.github/workflows/build_cli.yml
