[package]
name = "webrogue-virgl"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
_lib = ["dep:webrogue-virgl-lib"]
lib-stub = ["_lib", "webrogue-virgl-lib/stub"]
lib-impl = ["_lib", "webrogue-virgl-lib/impl"]

[dependencies]
lazy_static = { workspace = true }
ash = { workspace = true, default-features = false }
webrogue-virgl-lib = { workspace = true, optional = true }
xxhash-rust = { workspace = true, features = ["xxh3"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, default-features = false, features = ["Win32_System_Memory", "Win32_System_SystemInformation", "Win32_System_Kernel", "Win32_System_Diagnostics_Debug"] }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, default-features = false, features = ["mm", "param"]}
libc = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }
